[package]
name = "counter-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = "1.3.0"
cw-storage-plus = "1.1.0"
cosmwasm-schema = "1.3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []
